"""
A list of keyboard actions.
"""
(CLIENT_NEXT_DESKTOP, CLIENT_PREV_DESKTOP, TOGGLE_STICK,
 NEXT_DESKTOP, PREV_DESKTOP,
 ICONIFY, MAXIMIZE,
 REQUEST_CLOSE, FORCE_CLOSE,
 SNAP_TOP, SNAP_BOTTOM, SNAP_LEFT, SNAP_RIGHT,
 LAYER_ABOVE, LAYER_BELOW, LAYER_TOP, LAYER_BOTTOM,
 LAYER_1, LAYER_2, LAYER_3, LAYER_4, LAYER_5,
 LAYER_6, LAYER_7, LAYER_8, LAYER_9,
 EXIT_WM) = range(27)
